### ISSUE TITLE
Not able to Create Service as default

### ISSUE THREAD

**Issue by tanmaynaik123** [camunda-consulting/code#57]
Hi @benhoffmann  ,
                                   I am getting error while project run as
![Screenshot from 2019-07-19 13-18-34](https://user-images.githubusercontent.com/49868648/61518705-dd043e00-aa27-11e9-9d4b-f7ec0e8a37c0.png)

```
Caused by: org.camunda.bpm.engine.exception.NullValueException: Cannot stop service org.camunda.bpm.platform.process-engine:type=default: no such service registered: service is null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[na:na]
	at org.camunda.bpm.engine.impl.util.EnsureUtil.generateException(EnsureUtil.java:380) ~[camunda-engine-7.10.0.jar:7.10.0]
	at org.camunda.bpm.engine.impl.util.EnsureUtil.ensureNotNull(EnsureUtil.java:54) ~[camunda-engine-7.10.0.jar:7.10.0]
	at org.camunda.bpm.engine.impl.util.EnsureUtil.ensureNotNull(EnsureUtil.java:49) ~[camunda-engine-7.10.0.jar:7.10.0]
```

**Comment by benhoffmann** [comment]
Hi @tanmaynaik123, I think your issue can be best handled in our forum: https://forum.camunda.org 

Also, please provide some more context when submitting your question there:
- what are you trying to run
- which are steps to reproduce your problem

Best,
Ben
